### ISSUE TITLE
Bien hecho!

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/m3-evaluacion-intermedia-alexandrajaramz#1]
Buen trabajo @alexandrajaramz  !

Cinco pistas para dejarlo más fetén que fetén:

- [x] Usa el `id` de cada pokemon para el  `key` de react cuando mapeas y creas un listado de componentes
- [x] Usa propTypes para comprobar el tipo de dato de las props en TODOS los componentes que usan props
- [x] Revisa los metadatos en index.html (lang, title...)
- [x] Publica en Github Pages
- [x] Elimina archivos sin usar y sus referencias

Cuando tengas esto puedes:

1. Añadir un click a Pokemon que: marca o desmarca el pokemon como favorito en el array del estado de App.
1. Pasar este dato al componente Pokemon por props
1. Pintar Pokemon con otros estilos cuando por props nos llegue la info de que el pokemon es favorito

Si tienes cualquier duda, avisa!

Al turrón

**Comment by alexandrajaramz** [comment]
Ya he resuelto los cambios, los extras de favoritos los intentaré el finde con más tiempo :)

**Comment by oneeyedman** [comment]
Buen trabajo!
